import { Tabla } from "./app.types";

export const TABLA_CASETA: Tabla[] = [
  {nombre: 'Sucursal',indice: 'cedis',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Viaje',indice: 'viaje',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Estado del viaje',indice: 'estado',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Entrada',indice: 'entrada',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Salida',indice: 'salida',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Placa del vehículo',indice: 'placaVehiculo',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Clave del vehículo',indice: 'claveVehiculo',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Vehículo',indice: 'descripcionVehiculo',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Tipo de vehículo',indice: 'descripcionTipoVehiculo',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Clave del chofer',indice: 'claveChofer',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Chofer',indice: 'nombreChofer',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Procesa el viaje',indice: 'usuarioTransito',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Tipo de documento',indice: 'tipoRemision',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Origen',indice: 'folioRemision',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Chofer de la operación origen',indice: 'choferRemision',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Movimiento de almacén',indice: 'folioMovimientoAlmacen',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Clave del concepto',indice: 'claveConcepto',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Concepto',indice: 'nombreConcepto',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Procesa documento',indice: 'usuarioRemision',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Método de entrega',indice: 'metodoEntrega',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Operación',indice: 'folioOperacion',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Producto',indice: 'producto',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Unidad de medida',indice: 'unidad',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Longitud',indice: 'longitud',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Cantidad',indice: 'cantidad',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Peso',indice: 'peso',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Volumen',indice: 'volumen',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Cliente',indice: 'nombreCliente',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'RFC del cliente',indice: 'rfcCliente',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Razón social del cliente',indice: 'razonSocialCliente',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Tipo de venta',indice: 'tipoventa',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Nombre de la obra',indice: 'nombreObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Calle',indice: 'direccionObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Número exterior',indice: 'numeroExteriorObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Número interior',indice: 'numeroInteriorObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Colonia',indice: 'coloniaObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Localidad',indice: 'localidadObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Municipio',indice: 'municipioObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Estado',indice: 'estadoObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'País',indice: 'paisObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Código postal',indice: 'codigoPostal',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Cantidad Tn obra',indice: 'cantidadTonelajeObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Toneladas obra',indice: 'tonelajedObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'Cantidad M3 obra',indice: 'cantidadVolumenObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
  {nombre: 'M3 obra',indice: 'volumenObra',visible: true,tipo: 'number',class: '',ancho:'200px'},
];

export const CABECERAS = TABLA_CASETA.filter(i => i.visible).map(col => col.indice);